# Generated by Django 2.1.3 on 2018-12-18 10:14

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(help_text='Banner Image', upload_to='', verbose_name='Banner Image')),
                ('title', models.CharField(help_text='Title', max_length=100, verbose_name='Title')),
                ('below_image', models.ImageField(help_text='Below Image', upload_to='', verbose_name='Below Image')),
                ('below_title', models.CharField(help_text='Below Title', max_length=100, verbose_name='Below Title')),
                ('below_detail', ckeditor.fields.RichTextField(help_text='Below Detail', verbose_name='Below Detail')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created At', verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Modified At', verbose_name='Modified At')),
                ('products', models.ManyToManyField(help_text='Products', to='products.Product', verbose_name='Products')),
            ],
            options={
                'verbose_name': 'Start Detail',
                'verbose_name_plural': 'Start Details',
            },
        ),
    ]
