# Generated by Django 2.1.2 on 2018-11-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0005_auto_20181101_0443'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=100)),
                ('below_image', models.ImageField(upload_to='')),
                ('below_title', models.ImageField(upload_to='')),
                ('below_detail', models.TextField()),
                ('products', models.ManyToManyField(to='products.Product')),
            ],
        ),
    ]
