# Generated by Django 2.1.3 on 2018-11-04 15:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0002_auto_20181101_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='startdetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='startdetail',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
