# Generated by Django 2.1.3 on 2018-11-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0003_auto_20181104_1743'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='startdetail',
            options={'verbose_name': 'Start Detail', 'verbose_name_plural': 'Start Details'},
        ),
        migrations.AlterField(
            model_name='startdetail',
            name='banner_image',
            field=models.ImageField(help_text='Banner Image', upload_to='', verbose_name='Banner Image'),
        ),
        migrations.AlterField(
            model_name='startdetail',
            name='below_detail',
            field=models.TextField(help_text='Below Detail', verbose_name='Below Detail'),
        ),
        migrations.AlterField(
            model_name='startdetail',
            name='below_image',
            field=models.ImageField(help_text='Below Image', upload_to='', verbose_name='Below Image'),
        ),
        migrations.AlterField(
            model_name='startdetail',
            name='below_title',
            field=models.CharField(help_text='Below Title', max_length=100, verbose_name='Below Title'),
        ),
        migrations.AlterField(
            model_name='startdetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Created At', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='startdetail',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, help_text='Modified At', verbose_name='Modified At'),
        ),
        migrations.AlterField(
            model_name='startdetail',
            name='products',
            field=models.ManyToManyField(help_text='Products', to='products.Product', verbose_name='Products'),
        ),
        migrations.AlterField(
            model_name='startdetail',
            name='title',
            field=models.CharField(help_text='Title', max_length=100, verbose_name='Title'),
        ),
    ]
