# Generated by Django 2.1.2 on 2018-11-07 08:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0004_auto_20181104_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startdetail',
            name='below_detail',
            field=ckeditor.fields.RichTextField(help_text='Below Detail', verbose_name='Below Detail'),
        ),
    ]
