# Generated by Django 2.1.3 on 2018-12-18 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title', max_length=50, verbose_name='Title')),
                ('year', models.IntegerField(help_text='Year', verbose_name='Year')),
                ('details', models.TextField(help_text='Details', verbose_name='Details')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created At', verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Modified At', verbose_name='Modified At')),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
            },
        ),
        migrations.CreateModel(
            name='ArtisanMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created At', verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Modified At', verbose_name='Modified At')),
                ('seller', models.ForeignKey(help_text='Seller', on_delete=django.db.models.deletion.CASCADE, to='userprofile.Seller', verbose_name='Seller')),
            ],
            options={
                'verbose_name': 'Artisan Master',
                'verbose_name_plural': 'Artisan Masters',
            },
        ),
        migrations.CreateModel(
            name='Tale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title', max_length=50, verbose_name='Title')),
                ('details', models.TextField(help_text='Details', verbose_name='Details')),
                ('video_url', models.URLField(help_text='Video Url', verbose_name='Video Url')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created At', verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Modified At', verbose_name='Modified At')),
            ],
            options={
                'verbose_name': 'Tale',
                'verbose_name_plural': 'Tales',
            },
        ),
        migrations.AddField(
            model_name='achievement',
            name='artisan_master',
            field=models.ForeignKey(help_text='Artisan Master', on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='stories.ArtisanMaster', verbose_name='Artisan Master'),
        ),
    ]
