# Generated by Django 2.1.2 on 2018-11-01 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0002_auto_20181101_0331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ArtisanMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.Seller')),
            ],
        ),
        migrations.AddField(
            model_name='achievements',
            name='artisan_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='stories.ArtisanMaster'),
        ),
    ]
