# Generated by Django 2.1.2 on 2018-11-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_auto_20181101_0511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('details', models.TextField()),
                ('video_url', models.URLField()),
            ],
        ),
    ]
