# Generated by Django 2.1.2 on 2018-11-01 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_tales'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tales',
            new_name='Tale',
        ),
    ]
