# Generated by Django 2.1.3 on 2018-11-04 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_auto_20181104_1743'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'verbose_name': 'Achievement', 'verbose_name_plural': 'Achievements'},
        ),
        migrations.AlterModelOptions(
            name='artisanmaster',
            options={'verbose_name': 'Artisan Master', 'verbose_name_plural': 'Artisan Maters'},
        ),
        migrations.AlterModelOptions(
            name='tale',
            options={'verbose_name': 'Tale', 'verbose_name_plural': 'Tales'},
        ),
        migrations.AlterField(
            model_name='achievement',
            name='artisan_master',
            field=models.ForeignKey(help_text='Artisan Master', on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='stories.ArtisanMaster', verbose_name='Artisan Master'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Created At', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='details',
            field=models.TextField(help_text='Details', verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, help_text='Modified At', verbose_name='Modified At'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='title',
            field=models.CharField(help_text='Title', max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='year',
            field=models.IntegerField(help_text='Year', verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='artisanmaster',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Created At', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='artisanmaster',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, help_text='Modified At', verbose_name='Modified At'),
        ),
        migrations.AlterField(
            model_name='artisanmaster',
            name='seller',
            field=models.ForeignKey(help_text='Seller', on_delete=django.db.models.deletion.CASCADE, to='userprofile.Seller', verbose_name='Seller'),
        ),
        migrations.AlterField(
            model_name='tale',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Created At', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='tale',
            name='details',
            field=models.TextField(help_text='Details', verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='tale',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, help_text='Modified At', verbose_name='Modified At'),
        ),
        migrations.AlterField(
            model_name='tale',
            name='title',
            field=models.CharField(help_text='Title', max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='tale',
            name='video_url',
            field=models.URLField(help_text='Video Url', verbose_name='Video Url'),
        ),
    ]
