# Generated by Django 2.1.3 on 2018-11-06 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_auto_20181104_2337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artisanmaster',
            options={'verbose_name': 'Artisan Master', 'verbose_name_plural': 'Artisan Masters'},
        ),
    ]
