# Generated by Django 2.1.3 on 2018-12-18 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(blank=True, help_text='Avatar', max_length=50, null=True, verbose_name='Avatar')),
                ('phone_number', models.CharField(blank=True, help_text='Phone Number', max_length=15, null=True, verbose_name='Phone Number')),
                ('address', models.CharField(blank=True, help_text='Address', max_length=250, null=True, verbose_name='Address')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created At', verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Modified At', verbose_name='Modified At')),
                ('user', models.OneToOneField(help_text='User', on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Buyer',
                'verbose_name_plural': 'Buyers',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name', max_length=50, verbose_name='name')),
                ('phone', models.CharField(help_text='phone_number', max_length=15, verbose_name='phone_number')),
                ('email', models.EmailField(help_text='email', max_length=50, verbose_name='email')),
                ('message', models.TextField(help_text='message', max_length=500, verbose_name='message')),
                ('read', models.BooleanField(default=False, help_text='Done', verbose_name='Done')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created At', verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(help_text='Details', verbose_name='Details')),
                ('rate', models.FloatField(help_text='Rate', verbose_name='Rate')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created At', verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Modified At', verbose_name='Modified At')),
                ('buyer', models.ForeignKey(blank=True, help_text='Buyer', null=True, on_delete=django.db.models.deletion.SET_NULL, to='userprofile.Buyer', verbose_name='Buyer')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name', max_length=50, verbose_name='Name')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude', max_digits=9, null=True, verbose_name='Longitude')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude', max_digits=9, null=True, verbose_name='Latitude')),
                ('address', models.TextField(help_text='Address', verbose_name='Address')),
                ('avatar', models.ImageField(help_text='Avatar', upload_to='', verbose_name='Avatar')),
                ('description', models.TextField(help_text='Description', verbose_name='Description')),
                ('rate', models.FloatField(default=0.0, help_text='Rate', verbose_name='Rate')),
                ('number_of_rates', models.IntegerField(default='0', help_text='Number', verbose_name='Number')),
                ('phone_number', models.CharField(help_text='Phone Number', max_length=20, verbose_name='Phone Number')),
                ('APIKEY', models.CharField(blank=True, max_length=100, null=True)),
                ('merchant_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created At', verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Modified At', verbose_name='Modified At')),
                ('city', models.ForeignKey(blank=True, help_text='City', null=True, on_delete=django.db.models.deletion.SET_NULL, to='userprofile.City', verbose_name='City')),
                ('user', models.OneToOneField(help_text='User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Seller',
                'verbose_name_plural': 'Sellers',
            },
        ),
        migrations.AddField(
            model_name='review',
            name='seller',
            field=models.ForeignKey(blank=True, help_text='Seller', null=True, on_delete=django.db.models.deletion.SET_NULL, to='userprofile.Seller', verbose_name='Seller'),
        ),
    ]
