# Generated by Django 2.1.3 on 2018-12-28 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Avatar', null=True, upload_to='', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='review',
            name='seller',
            field=models.ForeignKey(blank=True, help_text='Seller', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='userprofile.Seller', verbose_name='Seller'),
        ),
    ]
