# Generated by Django 2.1.2 on 2018-11-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='rate',
            field=models.FloatField(default=0.0),
        ),
    ]
