# Generated by Django 2.1.3 on 2018-12-28 20:23

from django.db import migrations
import likert_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20181228_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=likert_field.models.LikertField(blank=True, help_text='Rate', null=True, verbose_name='Rate'),
        ),
    ]
