# Generated by Django 2.1.3 on 2019-01-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20181228_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='full_name',
            field=models.CharField(blank=True, help_text='full_name', max_length=150, null=True, verbose_name='full_name'),
        ),
        migrations.AddField(
            model_name='buyer',
            name='national_id',
            field=models.CharField(blank=True, help_text='national_id', max_length=20, null=True, verbose_name='national_id'),
        ),
    ]
