# Generated by Django 2.1.3 on 2019-01-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20190124_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='account_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
