# Generated by Django 2.1.3 on 2018-11-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_auto_20181104_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='number_of_rates',
            field=models.IntegerField(default='0'),
        ),
    ]
