# Generated by Django 2.1.3 on 2019-03-08 09:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_seller_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='name',
            field=models.CharField(help_text='Name', max_length=50, validators=[django.core.validators.RegexValidator(message='Should be a saudi phone number', regex='^[a-zA-Z\\s]*$')], verbose_name='Name'),
        ),
    ]
