# Generated by Django 2.1.3 on 2018-11-04 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_auto_20181104_2013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyer',
            options={'verbose_name': 'Buyer', 'verbose_name_plural': 'Buyers'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterModelOptions(
            name='seller',
            options={'verbose_name': 'Seller', 'verbose_name_plural': 'Sellers'},
        ),
        migrations.AddField(
            model_name='seller',
            name='address',
            field=models.TextField(default='', help_text='Address', verbose_name='Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='name',
            field=models.CharField(default='', help_text='Name', max_length=50, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buyer',
            name='address',
            field=models.CharField(blank=True, help_text='Address', max_length=250, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='avatar',
            field=models.CharField(blank=True, help_text='Avatar', max_length=50, null=True, verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Created At', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, help_text='Modified At', verbose_name='Modified At'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone Number', max_length=15, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='user',
            field=models.OneToOneField(help_text='User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='review',
            name='buyer',
            field=models.ForeignKey(blank=True, help_text='Buyer', null=True, on_delete=django.db.models.deletion.SET_NULL, to='userprofile.Buyer', verbose_name='Buyer'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Created At', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='review',
            name='details',
            field=models.TextField(help_text='Details', verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='review',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, help_text='Modified At', verbose_name='Modified At'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.FloatField(help_text='Rate', verbose_name='Rate'),
        ),
        migrations.AlterField(
            model_name='review',
            name='seller',
            field=models.ForeignKey(blank=True, help_text='Seller', null=True, on_delete=django.db.models.deletion.SET_NULL, to='userprofile.Seller', verbose_name='Seller'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='avatar',
            field=models.ImageField(help_text='Avatar', upload_to='', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='city',
            field=models.ForeignKey(blank=True, help_text='City', null=True, on_delete=django.db.models.deletion.SET_NULL, to='userprofile.City', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Created At', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='description',
            field=models.TextField(help_text='Description', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude', max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude', max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, help_text='Modified At', verbose_name='Modified At'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='number_of_rates',
            field=models.IntegerField(default='0', help_text='Number', verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='phone_number',
            field=models.CharField(help_text='Phone Number', max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='rate',
            field=models.FloatField(default=0.0, help_text='Rate', verbose_name='Rate'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='user',
            field=models.OneToOneField(help_text='User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
