# Generated by Django 2.1.3 on 2018-11-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_auto_20181104_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name', max_length=50, verbose_name='name')),
                ('phone', models.CharField(help_text='phone_number', max_length=15, verbose_name='phone_number')),
                ('email', models.EmailField(help_text='email', max_length=50, verbose_name='email')),
                ('message', models.TextField(help_text='message', max_length=500, verbose_name='message')),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
            },
        ),
    ]
