# Generated by Django 2.1.3 on 2018-11-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0010_contact_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='read',
            field=models.BooleanField(default=False, help_text='Done', verbose_name='Done'),
        ),
    ]
