# Generated by Django 2.1.3 on 2018-11-11 19:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0011_auto_20181111_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Created At', verbose_name='Created At'),
            preserve_default=False,
        ),
    ]
