# Generated by Django 2.1.3 on 2019-03-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
