# Generated by Django 2.1.2 on 2018-11-01 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20181101_0308'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAdditionalAttributeName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductAdditionalAttributeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_attribute_value', models.CharField(max_length=120)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='dimensions',
        ),
        migrations.RemoveField(
            model_name='product',
            name='material',
        ),
        migrations.AddField(
            model_name='productadditionalattributevalue',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='additional_attributes', to='products.Product'),
        ),
        migrations.AddField(
            model_name='productadditionalattributevalue',
            name='product_additional_attribute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_additional_attributes', to='products.ProductAdditionalAttributeName'),
        ),
    ]
