# Generated by Django 2.1.3 on 2019-03-12 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_auto_20190308_1202'),
        ('products', '0002_cart_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastProductsInCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.ForeignKey(help_text='Buyer', on_delete=django.db.models.deletion.CASCADE, to='userprofile.Buyer', verbose_name='Buyer')),
                ('carts', models.ManyToManyField(to='products.Product')),
            ],
        ),
        migrations.RemoveField(
            model_name='cart',
            name='show',
        ),
    ]
