# Generated by Django 2.1.2 on 2018-11-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20181101_0416'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
