# Generated by Django 2.1.3 on 2018-11-02 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20181102_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='sub_category',
        ),
    ]
