# Generated by Django 2.1.3 on 2018-11-03 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20181102_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='big_category',
        ),
        migrations.DeleteModel(
            name='BigCategory',
        ),
    ]
