# Generated by Django 2.1.3 on 2018-11-04 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20181104_1743'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Cart', 'verbose_name_plural': 'Carts'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productadditionalattributename',
            options={'verbose_name': 'Product Additional Attribute Name', 'verbose_name_plural': 'Product Additional Attribute Names'},
        ),
        migrations.AlterModelOptions(
            name='productadditionalattributevalue',
            options={'verbose_name': 'Product Additional Attribute Value', 'verbose_name_plural': 'Product Additional Attribute Values'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Product Image', 'verbose_name_plural': 'Product Images'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Sub Category', 'verbose_name_plural': 'Sub Categories'},
        ),
        migrations.AlterField(
            model_name='cart',
            name='buyer',
            field=models.ForeignKey(help_text='Buyer', on_delete=django.db.models.deletion.CASCADE, to='userprofile.Buyer', verbose_name='Buyer'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Created At', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, help_text='Modified At', verbose_name='Modified At'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(help_text='Product', on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(help_text='Quantity', verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Created At', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(help_text='Description', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(help_text='Image', upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, help_text='Modified At', verbose_name='Modified At'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Name', max_length=35, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Created At', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(help_text='Description', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, help_text='Modified At', verbose_name='Modified At'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Name', max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(help_text='Price', verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(help_text='Seller', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_products', to='userprofile.Seller', verbose_name='Seller'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(help_text='Sub Category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategory_products', to='products.SubCategory', verbose_name='Sub Category'),
        ),
        migrations.AlterField(
            model_name='productadditionalattributename',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Created At', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='productadditionalattributename',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, help_text='Modified At', verbose_name='Modified At'),
        ),
        migrations.AlterField(
            model_name='productadditionalattributename',
            name='name',
            field=models.CharField(help_text='Name', max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='productadditionalattributevalue',
            name='additional_attribute_value',
            field=models.CharField(help_text='Additional Attributes Values', max_length=120, verbose_name='Additional Attributes Values'),
        ),
        migrations.AlterField(
            model_name='productadditionalattributevalue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Created At', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='productadditionalattributevalue',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, help_text='Modified At', verbose_name='Modified At'),
        ),
        migrations.AlterField(
            model_name='productadditionalattributevalue',
            name='product',
            field=models.ForeignKey(help_text='Product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='additional_attributes', to='products.Product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='productadditionalattributevalue',
            name='product_additional_attribute',
            field=models.ForeignKey(help_text='Product Additional Attributes', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_additional_attributes', to='products.ProductAdditionalAttributeName', verbose_name='Product Additional Attributes'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(help_text='Alt Text', max_length=100, verbose_name='Alt Text'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Created At', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(help_text='Image', upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, help_text='Modified At', verbose_name='Modified At'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='order',
            field=models.IntegerField(help_text='Order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(help_text='Product', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.Product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(help_text='Category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='products.Category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Created At', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(help_text='Image', upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, help_text='Modified At', verbose_name='Modified At'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(help_text='Name', max_length=50, verbose_name='Name'),
        ),
    ]
