# Generated by Django 2.1.3 on 2018-11-06 19:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20181104_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, help_text='Description', verbose_name='Description'),
            preserve_default=False,
        ),
    ]
