# Generated by Django 2.1.3 on 2018-11-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cart',
            field=models.ManyToManyField(related_name='carts', to='products.Cart'),
        ),
    ]
