# Generated by Django 2.1.3 on 2018-11-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20181127_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ManyToManyField(related_name='carts', to='products.Cart'),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
