# Generated by Django 2.1.2 on 2018-12-03 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20181203_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('products.order',),
        ),
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(default=None, help_text='you can change the status form the states list', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Status'),
        ),
    ]
