# Generated by Django 2.1.3 on 2018-12-11 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0014_auto_20181204_1725'),
        ('products', '0024_auto_20181204_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seller',
            field=models.ForeignKey(default=2, help_text='Seller', on_delete=django.db.models.deletion.CASCADE, to='userprofile.Seller', verbose_name='Seller'),
        ),
    ]
